repos:

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.27.1
  hooks:
  - id: markdownlint
    name: markdown linting

- repo: https://github.com/yelp/detect-secrets.git
  rev: v1.1.0
  hooks:
  -   id: detect-secrets
      name: Detect Secrets (Yelp)
      args: ['--baseline', '.secrets.baseline']
      exclude: .*/go.sum

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
